name: 'Swift'
description: ''
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  args:
    description: ''
    default: '--help'
    required: true
outputs:
  result:
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}