name: 'Swift'
description: ''
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  subcommand:
    description: ''
    default: '--help'
    required: true
  arguments:
    description: ''
    required: false
outputs:
  result:
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'