name: YouTube-DL

on: [push]

jobs:
  youtube_dl:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: ./
    - name: Download
      id: download
      uses: actions/youtube_dl@v1
      with:
      url: 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc'
    - name: Get the output tim
      run: echo "Result: ${{ steps.download.outputs.result }}"