name: YouTube-DL

on:
  push:
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'

jobs:
  youtube_dl:
    runs-on: ubuntu-latest
    name: A job to download videos
    steps:
    - uses: actions/checkout@master
    - name: Download
      id: download
      uses: ./.github/actions/youtube_dl
      with:
        url: 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc'
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: Video
        path: ./Video