name: Swift

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Swift Package
    steps:
    - uses: actions/checkout@master
    - name: Build Package
      id: build
      uses: ./.github/actions/swift_packaging
      with:
        args: 'build'
    - name: Upload Build Archive
      uses: actions/upload-artifact@master
      with:
        name: 'Build Archive'
        path: ./