name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download
        run: |
          curl https://mailchi.mp/d891d51382cd/ambassadors > file.txt
      - name: contents
        run: |
          cat file.txt